### ISSUE TITLE
Not compatible with Angular 1.6.x

### ISSUE THREAD

**Issue by ghost** [logbon72/angular-material-datetimepicker#80]
A project that was working fine on 1.5.9 fails to open the date popup on 1.6.1. The following error is generated in the console:

TypeError: Cannot read property 'params' of undefined
    at new controller (http://localhost:3000/node_modules/angular-material-datetimepicker/js/angular-material-datetimepicker.js:523:34)
    at Object.invoke (http://localhost:3000/node_modules/angular/angular.min.js:43:175)
    at R.instance (http://localhost:3000/node_modules/angular/angular.min.js:93:35)
    at n (http://localhost:3000/node_modules/angular/angular.min.js:68:42)
    at g (http://localhost:3000/node_modules/angular/angular.min.js:60:496)
    at g (http://localhost:3000/node_modules/angular/angular.min.js:61:12)
    at g (http://localhost:3000/node_modules/angular/angular.min.js:61:12)
    at g (http://localhost:3000/node_modules/angular/angular.min.js:61:12)
    at n (http://localhost:3000/node_modules/angular/angular.min.js:69:166)
    at g (http://localhost:3000/node_modules/angular/angular.min.js:60:496) Possibly unhandled rejection: {}

**Comment by mingaila** [comment]
Same here. Anyone found solution?

**Comment by pmccorison** [comment]
Something with the two-way bindings between the md-dialog and the directive they have defined is not hooking up correctly with the latest update. Not sure if this is an angular problem with the update, or if the way the plugin is utilizing bindToController in this context is incorrect. As a result, the picker scope variable is not being passed to the child directives scope which is bound to the controller instead of scope.

This isn't a great solution, but appears to get us going until an official fix is done. You can access the parent scope through $scope.$parent, so you can change the following on the mdcDatetimePickerCalendar directive definition around line 528:

`var calendar = this,
                        picker = this.picker,
                        days = [];`

to 

`var calendar = this,
                        picker = $scope.$parent.picker,
                        days = [];`

Just a surface level check appears that things still work without utilizing an isolated scope for that variable. I'll post again if we see any issues. Once I get some more time, I might investigate this further.

**Comment by pmaganti** [comment]
Accessing through parent scope is working fine and a temporary fix.

We generate builds automatically and changing that line after build is hard to do everytime especially running on dist.

**Comment by sandeepzgk** [comment]
Please note that the fix suggested by @pmccorison works only with the unreleased version (if you are using it from release version 1.4.0) it would be different.

**Comment by hexadecy** [comment]
https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$compile
